spot_g6_12xlarge_node_ip_1 = ""
spot_g6_12xlarge_node_ip_2 = ""
spot_g6_12xlarge_node_ip_3 = ""
spot_g5_12xlarge_node_ip_1 = ""
spot_g5_12xlarge_node_ip_2 = ""
spot_g6e_xlarge_node_ip_1  = ""
spot_g6e_xlarge_node_ip_2  = ""
spot_g6e_xlarge_node_ip_3  = ""
spot_g6e_xlarge_node_ip_4  = ""

# The one g6.12xlarge spot instance is consistently available.
# on_demand_g6_12xlarge_node_ip_1 = ""
on_demand_g6_12xlarge_node_ip_2 = ""
on_demand_g6_12xlarge_node_ip_3 = ""
on_demand_g5_12xlarge_node_ip_1 = ""
on_demand_g5_12xlarge_node_ip_2 = ""
on_demand_g6e_xlarge_node_ip_1  = ""
on_demand_g6e_xlarge_node_ip_2  = ""
on_demand_g6e_xlarge_node_ip_3  = ""
on_demand_g6e_xlarge_node_ip_4  = ""